# Generated by Django 5.1.7 on 2025-04-29 13:42

import meals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('name', 'Food Name'), ('image', 'Food Image')], max_length=10)),
                ('food_name', models.CharField(blank=True, max_length=255, null=True)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('quantity', models.FloatField()),
                ('units', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms')], max_length=10)),
                ('time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default=mymeals.models.get_default_meal_time, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
