# Generated by Django 5.1.7 on 2025-04-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='food_name',
            field=models.CharField(blank=True, choices=[('apple', 'Apple'), ('banana', 'Banana'), ('rice', 'Rice'), ('chicken', 'Chicken'), ('egg', 'Egg'), ('bread', 'Bread'), ('milk', 'Milk'), ('carrot', 'Carrot'), ('potato', 'Potato'), ('orange', 'Orange')], max_length=255, null=True),
        ),
    ]
