# Generated by Django 5.1.7 on 2025-04-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='food_name',
            field=models.CharField(blank=True, choices=[('apple', 'Apple'), ('banana', 'Banana'), ('rice', 'Rice'), ('chicken', 'Chicken'), ('egg', 'Egg'), ('bread', 'Bread'), ('milk', 'Milk'), ('carrot', 'Carrot'), ('potato', 'Potato'), ('orange', 'Orange'), ('broccoli', 'Broccoli'), ('cheese', 'Cheese'), ('yogurt', 'Yogurt'), ('beef', 'Beef'), ('tofu', 'Tofu'), ('fish', 'Fish'), ('pasta', 'Pasta'), ('spinach', 'Spinach'), ('tomato', 'Tomato'), ('cucumber', 'Cucumber'), ('grapes', 'Grapes'), ('mango', 'Mango'), ('pineapple', 'Pineapple'), ('watermelon', 'Watermelon'), ('nuts', 'Nuts')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='units',
            field=models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('mg', 'Milligrams'), ('lb', 'Pounds'), ('oz', 'Ounces'), ('ml', 'Milliliters'), ('l', 'Liters'), ('cup', 'Cups'), ('tbsp', 'Tablespoons'), ('tsp', 'Teaspoons'), ('piece', 'Pieces'), ('slice', 'Slices'), ('bowl', 'Bowls'), ('plate', 'Plates'), ('serving', 'Servings'), ('can', 'Cans'), ('pack', 'Packs'), ('bottle', 'Bottles')], max_length=10),
        ),
    ]
